name: "Suno Kule"
version: "0.0.1-preview"
slug: "sunokule"
description: "Realtime WLED visual programming for Home Assistant"
url: "https://github.com/rikkertkoppes/ha-suno-kule"
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
ingress: true
ingress_port: 3001
homeassistant_api: true
hassio_api: true
panel_icon: mdi:led-strip-variant
panel_title: Suno Kule
ports: {}
ports_description: {}

image: "ghcr.io/rikkertkoppes/ha-suno-kule-{arch}"
